---
paths:
  yaml_path_rel: '../src/yaml'
  json_path_rel: '../converted/json'
  json_examples_path_rel: '../examples/json'
  md_path_rel: '../doc/markdown'
  md_web_path_rel: '../../ga4gh-schemablocks.github.io/pages/_schemas'
  github_repository_path: 'https://github.com/ga4gh-schemablocks/blocks/blob/master'
generator_prefix: '+generated__'
